### ISSUE TITLE
在RecyclerView中 不能显示

### ISSUE THREAD

**Issue by yu-guorong** [nex3z/FlowLayout#1]
自己写了个Demo，可以正常显示的，在RecyclerView的adapter中动态添加TextView 不能显示，将FlowLayout更换为LinearLayout，TextView能够显示。

**Comment by nex3z** [comment]
我在 c9006b72a799d7b070b04c2690c0d0ffcfd4333a 这里做了修复，可以先取用，效果如下图：

![screenshot_2017-03-16-00-06-57-966_com nex3z flowlayout sample](https://cloud.githubusercontent.com/assets/5645004/23958780/1d4a9172-09de-11e7-9c99-3f207d8630ed.png)

预计这周会发一个release解决此问题，谢谢反馈~
