### ISSUE TITLE
Is there a way to set layout's gravity?

### ISSUE THREAD

**Issue by zlluvhaj** [nex3z/FlowLayout#10]
The question is in the title pretty much. I would like to set vertical gravity to center, but I am not sure if that's possible.

**Comment by nex3z** [comment]
I'm adding the support for gravity in next release. 

You could try:
```
compile 'com.nex3z:flow-layout:1.1.1'
```

```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow"
    android:layout_width="match_parent"
    android:layout_height="300dp"
    android:gravity="center_vertical"
    android:background="@android:color/darker_gray"
    app:flChildSpacing="auto"
    app:flRowSpacing="8dp"/>
```
The layout above will produce:
![device-2017-11-29-122255](https://user-images.githubusercontent.com/5645004/33359557-5623deca-d50a-11e7-801c-a7a21d352ee5.png)

**Comment by zlluvhaj** [comment]
Sorry for not replying, but I forgot to say that I would like to do this programmatically. Thank you for the XML, though! I tried the 1.1.1 version, but the method wasn't there yet I saw.

**Comment by nex3z** [comment]
I've added a setGravity() method in 1.1.2 version:

```
compile 'com.nex3z:flow-layout:1.1.2'
```

Now you could use:

```java
flowLayout.setGravity(Gravity.CENTER_VERTICAL);
```

**Comment by zlluvhaj** [comment]
Thank you so much, appreciate the support!

**Comment by zlluvhaj** [comment]
Sorry, but it seems to be centering only horizontally..
With Gravity.CENTER_VERTICAL:
https://i.imgur.com/OUs6fHM.png

With Gravity.CENTER:
https://i.imgur.com/YT2uiTd.png

**Comment by nex3z** [comment]
Could you share the layout and your expectation? 

I suppose you want to center the text vertically. From the screenshot, I guess the height of the text is much smaller than the height of the image, or the text's gravity not set to `center_vertical`. You may try setting the height of the text to be the same as the height of the image, and set `android:gravity="center_vertical"` on the text.

For example:

```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow"
    android:layout_width="match_parent"
    android:layout_height="100dp"
    android:background="@android:color/darker_gray">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="50dp"
        android:gravity="center_vertical"
        android:text="Some text"/>

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="50dp"
        android:src="@android:drawable/ic_media_play" />

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="50dp"
        android:src="@android:drawable/ic_media_next" />

</com.nex3z.flowlayout.FlowLayout>
```

The layout above will produce:
![device-2017-12-03-225124](https://user-images.githubusercontent.com/5645004/33526446-cae62784-d87c-11e7-8392-7c46d2fb4b0c.png)

After calling `((FlowLayout) findViewById(R.id.flow)).setGravity(Gravity.CENTER_VERTICAL)`:
![device-2017-12-03-225225](https://user-images.githubusercontent.com/5645004/33526457-f15e1296-d87c-11e7-82fb-a924dfd8cd88.png)

But without `android:gravity="center_vertical"` on the `TextView`, it looks like:
![device-2017-12-03-225729](https://user-images.githubusercontent.com/5645004/33526496-66a86b46-d87d-11e7-8569-2e64de8fc263.png)

`FlowLayout` applys the gravity on all its child views as a whole. If you want to align the content of any specific child view, you need to change the configuration of that child view (change its size, gravity, etc).

**Comment by zlluvhaj** [comment]
Setting the TextView gravity to CENTER_VERTICAL and height to the same as ImageView did the trick.
I thought your FlowLayout would center content the same way as ApmeM's FlowLayout does (basically centering each view to one single line, not all childs as a whole).
As I couldn't use his FlowLayout, I had to search for an alternative and now yours is perfect, thank you!
