### ISSUE TITLE
flChildSpacing为auto时左右间距为0的问题

### ISSUE THREAD

**Issue by s949492225** [nex3z/FlowLayout#12]
问题:
       如果flChildSpacing设置为auto时,一行内的标签刚好和总宽度相等话,这时每个标签之间的间距就是0,看起来很不雅观.
建议:
       建议在auto的情况下允许设置minSpace,这样不管任何情况两个tag之间都有一个设置的最小间距.
谢谢作者的劳动

**Comment by nex3z** [comment]
在 `1.1.3` 版本添加了 `flMinChildSpacing` 属性，用于设置子 View 间的最小水平距离，当 `flChildSpacing` 为 `auto ` 时有效。

```
compile 'com.nex3z:flow-layout:1.1.3'
```

例如：
```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow2"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:flChildSpacing="auto"
    app:flMinChildSpacing="4dp"
    app:flChildSpacingForLastRow="align"
    app:flRowSpacing="8dp">

<!-- ... -->

</com.nex3z.flowlayout.FlowLayout>
```
![device-2018-02-08-181755](https://user-images.githubusercontent.com/5645004/35973993-65d18cc4-0d12-11e8-821e-f9aba7a088fe.png)

```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow2"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:flChildSpacing="auto"
    app:flMinChildSpacing="16dp"
    app:flChildSpacingForLastRow="align"
    app:flRowSpacing="8dp">

<!-- ... -->

</com.nex3z.flowlayout.FlowLayout>
```
![device-2018-02-08-181818](https://user-images.githubusercontent.com/5645004/35974008-73b0a906-0d12-11e8-987d-100d193dff11.png)
