### ISSUE TITLE
RTL Programmatically

### ISSUE THREAD

**Issue by sujan-lama** [nex3z/FlowLayout#14]
Why is not there setRtl true or false setter programatically? I want to set it according to language, but cannot set it. Is there any way?

**Comment by nex3z** [comment]
I've added getter/setter for `flRtl` attribute in v1.2.0.

```
implementation 'com.nex3z:flow-layout:1.2.0'
```

Usage:

```java
flowLayout.setRtl(true);
```

**Comment by sujan-lama** [comment]
Oh. Well, Thank you so much. 👍

**Comment by devilabhi** [comment]
But it is giving issues from right spacing

**Comment by nex3z** [comment]
> But it is giving issues from right spacing

Please create a new issue with more information (screenshots, layouts, etc), thanks.
