### ISSUE TITLE
flChildSpacing child spacing seems not to work

### ISSUE THREAD

**Issue by ghost** [nex3z/FlowLayout#16]
<com.nex3z.flowlayout.FlowLayout
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:flChildSpacing="auto"
            app:flChildSpacingForLastRow="align"
            app:flRowSpacing="8dp"
            >

I set up like this but when I set the flChildSpacing to a certain value, it seems to just then cram the view all together

**Comment by nex3z** [comment]
Could you please share your layout and a screenshot?

I tried the following layout:

```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow2"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:flChildSpacing="16dp"
    app:flChildSpacingForLastRow="align"
    app:flRowSpacing="8dp">

    <TextView
        android:layout_width="60dp"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:padding="8dp"
        android:background="@drawable/label_bg"
        android:text="@string/sun"/>

    <!--...-->

    <TextView
        android:layout_width="60dp"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:padding="8dp"
        android:background="@drawable/label_bg"
        android:text="@string/sat"/>

</com.nex3z.flowlayout.FlowLayout>
```

![device-2018-05-04-004731](https://user-images.githubusercontent.com/5645004/39590994-fd82790c-4f34-11e8-83cd-124504e607e2.png)
