### ISSUE TITLE
flChildSpacingForLastRow is useless

### ISSUE THREAD

**Issue by weiyalong1025** [nex3z/FlowLayout#17]
The tag flChildSpacingForLastRow="align" is useless when there only one line and app:flChildSpacing="auto".

**Comment by nex3z** [comment]
`align` in `childSpacingForLastRow` means that the horizontal spacing of the child views in the last row keeps the same with the spacing used in the row above, as documented in the [readme](https://github.com/nex3z/FlowLayout#attributes). If there is only one row in `FlowLayout`, there is no row above to align with, thus setting `childSpacingForLastRow` to `align` has no effect.
