### ISSUE TITLE
getRowCount

### ISSUE THREAD

**Issue by imaNNeo** [nex3z/FlowLayout#21]
Hi, i need a function to get the rows count, 
i added it by customizing your class in my project, but i think its better to add it on this repo, 
also i can send a merge request to add it if you haven't enough time.

**Comment by nex3z** [comment]
Of course. Please send your merge request. Thanks.

**Comment by nex3z** [comment]
Included in release v1.2.4.
```
compile 'com.nex3z:flow-layout:1.2.4'
```
