### ISSUE TITLE
setMaxRows and gravity don't seem to be working

### ISSUE THREAD

**Issue by mihir-kandoi** [nex3z/FlowLayout#24]
When I setMaxRows to 5 (or anything else) in onCreate, the layout simply ignores it and keeps adding views. Also when I set gravity to center, it instead treats it like center_vertical.

The weird part is the first 3 to 4 times I used it, it worked perfectly fine but now all of a sudden I keep on encountering these weird issues.

**Comment by nex3z** [comment]
Could you share your layout and your expected result?
