### ISSUE TITLE
Not able to center align elements if 2 rows have different number of views.

### ISSUE THREAD

**Issue by KhushbooR** [nex3z/FlowLayout#25]
I am trying to center align the elements in each row but always getting left or right alignment.

I have 5 rows with 14 elements, First row seems fine but issues are with the other rows in the layout.
> Either the elements of bottom rows are aligned such that left and right items are at extreme left and right places simultaneously (if child spacing is "auto").
> Or all the elements of particular row are shifted to the left (or right) aligned sequence (if child spacing is defined: lets say 10dp).

I need these items to be placed in center when I define the child spacing. 

Please give a solution on this.

**Comment by banyanstudio** [comment]
KhushbooR did you got solution for this problem ??

**Comment by KhushbooR** [comment]
> KhushbooR did you got solution for this problem ??

@DeepanJN Yes, I did this -->
`categoryFlowLayout.setGravity(Gravity.CENTER);`
This was not working with gravity set in xml.

**Comment by banyanstudio** [comment]
@KhushbooR thank you for helping!
