### ISSUE TITLE
change  flChildSpacing progamatically

### ISSUE THREAD

**Issue by banyanstudio** [nex3z/FlowLayout#28]
Hi, how to change params programmatically. like flChildSpacing

**Comment by nex3z** [comment]
There are getters/setters for spacing params, like [`getChildSpacing()`](https://github.com/nex3z/FlowLayout/blob/master/flowlayout/src/main/java/com/nex3z/flowlayout/FlowLayout.java#L372) and [`setChildSpacing(int childSpacing)`](https://github.com/nex3z/FlowLayout/blob/master/flowlayout/src/main/java/com/nex3z/flowlayout/FlowLayout.java#L382) for `flChildSpacing`.
