### ISSUE TITLE
onlayout在存在隐藏的子元素的时候计算错误

### ISSUE THREAD

**Issue by windern** [nex3z/FlowLayout#3]
不能再for循环后直接i++，因为如果遇到隐藏的子元素了，就跳过了，如果i++了，就这一行也会少显示一个元素，这是不对的，应该在最后成功了才i++
for (int i = 0; i < childNumInRow; ) {
                View child = getChildAt(childIdx++);
                if (child.getVisibility() == GONE) {
                    continue;
                }
               XXXXXX
               XXXXXX 
               //可以显示的才算这一行的元素，成功以后才i++
                i++;
}

**Comment by nex3z** [comment]
已修复，修复版本为v0.1.4，谢谢反馈！
```
compile 'com.nex3z:flow-layout:0.1.4'
```
