### ISSUE TITLE
Horizontal scroll view with Flow Layout

### ISSUE THREAD

**Issue by vladyhon** [nex3z/FlowLayout#30]
Hi, is it possible to add horizontal scroll view to flow layout with two rows? 
Because right now, If you add Horizontal Scroll View for flow layout, there will be only one row and scroll. Is it possible to make two rows?

**Comment by nex3z** [comment]
As the child view of HorizontalScrollView, FlowLayout will try to take as much space as possible in horizontal direction, thus there will be only one row.

If you need exactly two rows, one workaround is to calculate the width of each row and set a fixed `layout_width` value on FlowLayout.

For example, there are 16 items to be placed in two rows, each item is 60dp wide. Then there are 8 items in each row, and each row is 60dp * 8 = 480dp wide. The layout looks like

```xml
<HorizontalScrollView
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <FrameLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <com.nex3z.flowlayout.FlowLayout
            android:id="@+id/flow"
            android:layout_width="480dp"
            android:layout_height="wrap_content"
            app:flChildSpacing="auto"
            app:flRowSpacing="8dp" />

    </FrameLayout>

</HorizontalScrollView>
```

![device-2019-04-19-190432](https://user-images.githubusercontent.com/5645004/56421983-cb4fb500-62d7-11e9-9d77-8ba013c7408f.png)

**Comment by abdussamad123** [comment]
how can i use flowlayout for dynamic data with clickable view?
any help will be appreciated.

Thanks

**Comment by nex3z** [comment]
> how can i use flowlayout for dynamic data with clickable view? any help will be appreciated.
> 
> Thanks

Just add any clickable view and `setOnClickListener`.

Modified from [sample](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/java/com/nex3z/flowlayout/sample/MainActivity.java#L35):

```java
    private void fillAutoSpacingLayout() {
        FlowLayout flowLayout = findViewById(R.id.flow);
        String[] dummyTexts = getResources().getStringArray(R.array.lorem_ipsum);

        for (final String text : dummyTexts) {
            TextView textView = buildLabel(text);
            textView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    Toast.makeText(MainActivity.this.getApplicationContext(), text, Toast.LENGTH_SHORT).show();
                }
            });
            flowLayout.addView(textView);
        }
    }
```
