### ISSUE TITLE
Can we have the option to center all bubbles horizontal?

### ISSUE THREAD

**Issue by skinner2012** [nex3z/FlowLayout#37]
We can see all bubbles are left-aligned. Is there any option we can let all bubbles center or right-aligned? Thanks.

![image](https://user-images.githubusercontent.com/1660764/67727460-bb134380-f9a6-11e9-9078-77cb236e97c0.png)

**Comment by nex3z** [comment]
Just set `app:flChildSpacing` to a fixed dp value and change `android:gravity`.

For example,  set `android:gravity="center_horizontal"`: 

```xml
<com.nex3z.flowlayout.FlowLayout
	android:id="@+id/flow2"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:gravity="center_horizontal"
	android:background="@drawable/box"
	app:flChildSpacing="4dp"
	app:flRowSpacing="8dp">
...
</com.nex3z.flowlayout.FlowLayout>
```

![center](https://user-images.githubusercontent.com/5645004/67735617-a767eb80-fa3f-11e9-9c47-b08825c80ea9.png)

set `android:gravity="right"`: 

```xml
<com.nex3z.flowlayout.FlowLayout
	android:id="@+id/flow2"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:gravity="right"
	android:background="@drawable/box"
	app:flChildSpacing="4dp"
	app:flRowSpacing="8dp">
...
</com.nex3z.flowlayout.FlowLayout>
```

![right](https://user-images.githubusercontent.com/5645004/67735746-09c0ec00-fa40-11e9-8322-de5f2901c9d3.png)

**Comment by skinner2012** [comment]
Thank you!
