### ISSUE TITLE
Don't layout and render cut off items in single row

### ISSUE THREAD

**Issue by lwasyl** [nex3z/FlowLayout#38]
Currently with a single row and e.g. 10 children, it's possible to have just 4 items visible, fifth item visible partially and the rest hidden. One obvious use case for this behavior is with a scroll view, but I'd like to only show the fully visible items, and just drop the rest. 

Is it possible that such behavior is added to the library (I can try to contribute) or maybe it's possible with the existing API? I'd like to avoid measuring the items myself (since then they'd be measured twice, by me and by the flow layout) is possible

**Comment by nex3z** [comment]
There is a `app:flMaxRows` attribute which sets the maximum row count.

For example, setting `app:flMaxRows="1"` only shows the first row even if there are more items below.

```xml
<com.nex3z.flowlayout.FlowLayout
    android:id="@+id/flow"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/box"
    app:flChildSpacing="auto"
    app:flRowSpacing="8dp"
    app:flMaxRows="1"/>
```

![device-2019-11-05-162647](https://user-images.githubusercontent.com/5645004/68202003-d3660c80-fffd-11e9-8b90-8e35c5b2609f.png)

**Comment by lwasyl** [comment]
Perfect! It does work like this only with `flFlow = true` so I missed it initially. Thank you!
