### ISSUE TITLE
确保RecyclerView水平加入item

### ISSUE THREAD

**Issue by GyyBest** [nex3z/FlowLayout#4]
请问如何确保RecyclerView水平加入Itemview

**Comment by nex3z** [comment]
请问“水平加入”指的是向 FlowLayout 水平加入子 View，还是向 RecyclerView 加入水平滚动的 Item 呢？

[这里](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/java/com/nex3z/flowlayout/sample/RecyclerViewActivity.java)有一个在 RecyclerView 中使用 FlowLayout 的例子， 默认垂直滚动，如下图：

![device-2017-05-10-182036](https://cloud.githubusercontent.com/assets/5645004/25894378/2184958e-35ae-11e7-963d-2b1296f34f31.png)

注释掉 [第20行](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/java/com/nex3z/flowlayout/sample/RecyclerViewActivity.java#L20) 并打开 [第21行](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/java/com/nex3z/flowlayout/sample/RecyclerViewActivity.java#L21) 可以水平滚动。

**Comment by GyyBest** [comment]
我想要Flowlayout水平加入子view。
但是现在是垂直加入子view
![image](https://cloud.githubusercontent.com/assets/9551773/25898719/9788c884-358d-11e7-92d4-f8c273fe08f8.png)
我不知原因在哪儿

**Comment by nex3z** [comment]
建议按顺序检查一下 [FlowLayout 子 View 的宽度](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/item.xml#L15)、[FlowLayout / Item 的宽度](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/item.xml#L5)、[RecyclerView 的宽度](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/activity_recycler_view.xml#L11) 以及 [容纳 RecyclerView 的 ViewGroup 的宽度](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/activity_recycler_view.xml#L5)：是否 FlowLayout 子 View 的宽度过长，导致一个子 View 就占满了一行；或者 FlowLayout 及其父 ViewGroup 的宽度被限制住了，导致一行只能放下一个图标。

可以使用 [Layout Inspector](http://tools.android.com/tech-docs/layout-inspector) 来直观地查看各个 View 的布局和尺寸，如下图。

![1](https://cloud.githubusercontent.com/assets/5645004/25899406/4c78528a-35c2-11e7-918a-c763f991b2cc.png)

**Comment by GyyBest** [comment]
很感激回复
![image](https://cloud.githubusercontent.com/assets/9551773/25900393/b2d4b6ce-3593-11e7-9ed3-eebc039d6beb.png)
因为我只有一个子view，算法也是竖直加入的，所以请博主指点我这个android新手如何作出更改，谢谢了
![image](https://cloud.githubusercontent.com/assets/9551773/25900498/f26fd3ae-3593-11e7-8162-70aae9e4eba1.png)
这是我的item.xml
![image](https://cloud.githubusercontent.com/assets/9551773/25900522/02788034-3594-11e7-822d-7a00f71f7773.png)
这是我的recyclerview.xml

**Comment by GyyBest** [comment]
如果我注释掉 第20行 并打开 第21行 可以水平加入子view，但是我不想要滚动，而且这样也无法flow到第二行

**Comment by nex3z** [comment]
从截图里看，RecyclerView 里的每个 item 都有一个 PTFlowLayout，每个 PTFlowLayout 里面只有一个ImageView。

目测 RecyclerView 使用了垂直的 LinearLayoutManager，所以每一个 item 占一行，而 item 内只有包含了一个 ImageView 的 PTFlowLayout，导致了现在每个 ImageView 占一行的结果。

FlowLayout 作为一个 ViewGroup，会让其内部的子 View 在填满一行后，自动换到下一行，多个 FlowLayout 之间不会互相影响。图中的用法是创建了多个 FlowLayout，而每个 FlowLayout 里面只有一个 ImageView，所以这一个 ImageView 就占了一行。

如果你希望实现的是下图的效果：
![9788c884-358d-11e7-92d4-f8c273fe08f8](https://cloud.githubusercontent.com/assets/5645004/25901476/85305c7e-35c9-11e7-8ef3-4f97bcd65081.png)

可以尝试这么写 item.xml：
```xml
<com.unisc.pictotravel.ui.custom.PTFlowLayout
    ...>

    <!--第1个图标-->
    <ImageView 
        ... />
        
    <!--第2个图标-->
    <ImageView 
        ... />
	
    <!--第3个图标-->
    <ImageView 
        ... />
	   
        ...

</com.unisc.pictotravel.ui.custom.PTFlowLayout>
```

其实相当于是把 [这里](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/item.xml) 的 TextView 换成 ImageView。

**Comment by nex3z** [comment]
如果你只想要一行图标，像下图：
![2](https://cloud.githubusercontent.com/assets/5645004/25902096/23a9257e-35cb-11e7-9e3d-87bfcb3a564e.png)
在图标不是特别多的情况下，没有必要使用 RecyclerView，直接使用 FlowLayout 即可。

**Comment by GyyBest** [comment]
对的我只想要一行图标，但是这是个RecyclerView下的RecyclerView，我需要动态传图标数目给这个RecyclerView，也就是说，另一个View里的这个RecyclerView或许是[0,7]的任何一个数目，不知博主有何见解呢
![image](https://cloud.githubusercontent.com/assets/9551773/25902505/01fe03da-359a-11e7-88e6-07040dd9b726.png)

**Comment by nex3z** [comment]
FlowLayout 是一个 ViewGroup，可以通过 [`addView()`](https://developer.android.com/reference/android/view/ViewGroup.html#addView(android.view.View)) 动态地向 ViewGroup 添加子 View，比如 [这里](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/java/com/nex3z/flowlayout/sample/MainActivity.java#L35) 的用法：
```
private void fillAutoSpacingLayout() {
    FlowLayout flowLayout = (FlowLayout) findViewById(R.id.flow);
    String[] dummyTexts = getResources().getStringArray(R.array.lorem_ipsum);

    for (String text : dummyTexts) {
        TextView textView = buildLabel(text);
        flowLayout.addView(textView);
    }
}
```
就是在运行时从资源里读出一个字符串数组，然后创建显示对应字符串内容的 TextView，再把 TextView 添加到 FlowLayout 里面。

如果嫌 `addView()` 麻烦，还可以自己封装一个 Custom View，这个 Custom View 是一个 FlowLayout，里面预置了所有图标，对外提供一个类似 `setIconCount(int count)` 的接口，来方便地配置要显示多少个图标。

**Comment by GyyBest** [comment]
Yes! Perfect.
根据您的建议我没用RecyclerView，改用FlowLayout。现在是我想要的样子，十分感谢
![image](https://cloud.githubusercontent.com/assets/9551773/25942666/af058e10-363d-11e7-95e5-5e84e25cd982.png)
![image](https://cloud.githubusercontent.com/assets/9551773/25942685/bc7bf66a-363d-11e7-8828-6a179ae4f3ee.png)
