### ISSUE TITLE
FlowLayout children overdraw themselves

### ISSUE THREAD

**Issue by mateuszkwiecinski** [nex3z/FlowLayout#45]
Version 1.3.2 introducs a bug when `FlowLayout` is being reused i.e. on Recycleview.

On first layout it properly draws its children:
<img width="572" alt="Screenshot 2020-12-10 at 22 27 53" src="https://user-images.githubusercontent.com/36954793/101832030-12d32680-3b37-11eb-952e-4850e684981c.png">

but when the screen is scrolled and the container is reused its starts drawing over its children (or draws children that shouldn't be drawn?):
<img width="573" alt="Screenshot 2020-12-10 at 22 28 06" src="https://user-images.githubusercontent.com/36954793/101832032-14045380-3b37-11eb-84a8-8eb01801ac56.png">
<img width="573" alt="Screenshot 2020-12-10 at 22 28 06" src="https://user-images.githubusercontent.com/36954793/101832504-d653fa80-3b37-11eb-9a36-fe17054403b9.png">

That is how the view looks like without `app:flMaxRows="1"`:
<img width="573" alt="Screenshot 2020-12-10 at 22 28 06" src="https://user-images.githubusercontent.com/36954793/101832675-1ca95980-3b38-11eb-80c0-c37fb5b7f9b4.png">

FlowLayout setup:
```
<com.nex3z.flowlayout.FlowLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:flChildSpacing="4dp"
    app:flMaxRows="1"
    app:flRowSpacing="4dp"
    ><!-- children --> </com.nex3z.flowlayout.FlowLayout>
```

**Comment by nex3z** [comment]
I built a similar layout but cannot reproduce this issue.

![1](https://user-images.githubusercontent.com/5645004/101851610-d8997180-3b96-11eb-849a-a945ac55b02f.gif)

![1](https://user-images.githubusercontent.com/5645004/101851782-3037dd00-3b97-11eb-9d0a-eed2188172f9.PNG)

Could you please provide more code for reproducing this issue? 
And also could you please comfirm whether the issue is introduced only in 1.3.2 and not in 1.3.1? 
Thanks.

**Comment by mateuszkwiecinski** [comment]
Here's sample repository: https://github.com/mateuszkwiecinski/flowlayout_bug

It looks like the key thing is to set content that causes the child to resize. And yes the issue appeared in 1.3.2, it works well with 1.3.1

![ten](https://user-images.githubusercontent.com/36954793/101883563-b8b67d80-3b97-11eb-9d6d-13394948936e.gif)

**Comment by nex3z** [comment]
Please check 1.3.3:

```
implementation 'com.nex3z:flow-layout:1.3.3'
```

**Comment by mateuszkwiecinski** [comment]
Superb! Every thing works as expected. Thank you for the fix and for maintaining the library 🙏
