### ISSUE TITLE
Publish to mavenCentral

### ISSUE THREAD

**Issue by lwasyl** [nex3z/FlowLayout#47]
Bintray is getting shut down in 3 months, and right now FlowLayout is only available on jcenter.

See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ for details

**Comment by nex3z** [comment]
Publish on Maven Central. Please check https://search.maven.org/artifact/com.nex3z/flow-layout/1.3.3/aar

**Comment by lwasyl** [comment]
It seems to be working, thank you for maintaining the library :)
