### ISSUE TITLE
当我滑动很长的Flowlayout时，上方view底部会有重影

### ISSUE THREAD

**Issue by SkyD666** [nex3z/FlowLayout#48]
![Screenshot_20210214_123341_com skyd imomoe](https://user-images.githubusercontent.com/32453770/107868697-547aa780-6ec1-11eb-9636-c95d47bf440a.jpg)
![Screenshot_20210214_123749](https://user-images.githubusercontent.com/32453770/107868716-7d9b3800-6ec1-11eb-9095-92cd1d894398.jpg)

**Comment by nex3z** [comment]
我试了一下，没有复现这个问题：
![1](https://user-images.githubusercontent.com/5645004/107877908-31c0b100-6f0a-11eb-8cc7-cdce28377d99.png)
![2](https://user-images.githubusercontent.com/5645004/107877910-34230b00-6f0a-11eb-908b-0885081182dd.png)
![3](https://user-images.githubusercontent.com/5645004/107877911-34bba180-6f0a-11eb-88e7-839a0604bb6e.png)


可以用 [Layout Inspector](https://developer.android.com/studio/debug/layout-inspector)（Android Studio 中 Tools / Layout Inspector ）看一下下面这个界面中 FlowLayout 的范围，以及那四条线是从哪里来的。
![107868716-7d9b3800-6ec1-11eb-9095-92cd1d894398](https://user-images.githubusercontent.com/5645004/107877937-5b79d800-6f0a-11eb-96e5-039fe40add90.jpg)

**Comment by SkyD666** [comment]
我用Layout Inspector时，并不显示新手机上的这四条线。同时，我有我的旧手机红米3（MIUI9.8 安卓5.1.1）和旧手机OPPO A57（ColorOS V3.0 安卓6.0.1）也不显示这四条白线。只有我用新手机HONOR V20（Magic 2.1.0 安卓9）才有这四条线。感觉很奇怪

**Comment by nex3z** [comment]
如果那四条线在 FlowLayout 布局之外，可能是系统绘制问题。

下面的例子分别使用 FlowLayout 和 RecyclerView 实现了类似的布局，可以试试看能不能复现问题。对于有大量 View 的场景，使用 RecyclerView 更加效率。

[Sample.zip](https://github.com/nex3z/FlowLayout/files/5982249/Sample.zip)

**Comment by SkyD666** [comment]
那四条线确实在FlowLayout之外，线在上方的LinearLayout上面。感谢例子，我研究一下
