### ISSUE TITLE
flChildSpacing and flRowSpacing fix value can not preview but run ok

### ISSUE THREAD

**Issue by krmao** [nex3z/FlowLayout#49]
Flow layout has very nice! 
the preview about spacing fix value may be better!

thanks to author

![image](https://user-images.githubusercontent.com/7344437/112724381-093ac680-8f4e-11eb-92a4-3f2c3d7be018.png)

**Comment by nex3z** [comment]
可以试下

```
implementation 'com.nex3z:flow-layout:1.3.4-beta01'
```

![1](https://user-images.githubusercontent.com/5645004/112784562-91bb8300-9084-11eb-830b-b52fbef5e5ac.PNG)

**Comment by krmao** [comment]
It works like a charm !
