### ISSUE TITLE
Main Layout view disappears

### ISSUE THREAD

**Issue by NexoVentas-Android** [nex3z/FlowLayout#52]
When Iam add the Flowlayout into my layout then the preview in the split or the design mode disapears

Iam adding this way

  <com.nex3z.flowlayout.FlowLayout
                    android:id="@+id/flowLaySKUs"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_margin="10dp"
                    app:flChildSpacing="2dp"
                    app:flRowSpacing="2dp" />

**Comment by nex3z** [comment]
Try build the project and check the preview again. 

For example, check the [sample layout](https://github.com/nex3z/FlowLayout/blob/master/sample/src/main/res/layout/activity_main.xml) and you should be able to see the following preview after build. If not, please check if there is any error shown in the upper right corner of the preview window.

![image](https://user-images.githubusercontent.com/5645004/197223721-f8eea64d-e7ba-4a81-9bde-6b7db996b369.png)

**Comment by NexoVentas-Android** [comment]
Tried many times even i did inavlidate cache and restart but nothing happened

**Comment by nex3z** [comment]
Any error message shows up here?
![197223721-f8eea64d-e7ba-4a81-9bde-6b7db996b369](https://user-images.githubusercontent.com/5645004/199549192-be286a2b-a894-41e1-a16c-5914ea86668d.png)

**Comment by NexoVentas-Android** [comment]
Nope even iam not getting any warning

**Comment by NexoVentas-Android** [comment]
Not any Error occurs you see in the image

![Untitled](https://user-images.githubusercontent.com/94887681/199654315-f3a39835-c481-455f-8fbc-bff1d6c29356.png)

**Comment by nex3z** [comment]
Can you share this layout file?

**Comment by NexoVentas-Android** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".fragments.VisitsFragment">

        <TextView
            android:id="@+id/titleCart"
            android:layout_width="match_parent"
            android:layout_height="?actionBarSize"
            android:background="@color/appcolor"
            android:gravity="center"
            android:text="Visits"
            android:textColor="@color/white"
            android:textSize="22sp"
            android:textStyle="bold"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <LinearLayout
            android:id="@+id/layFilters"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:paddingHorizontal="@dimen/margin_10"
            app:layout_constraintTop_toBottomOf="@+id/titleCart">

            <FrameLayout
                android:id="@+id/laySorting"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content">

                <ImageView
                    android:layout_width="@dimen/margin_15"
                    android:layout_height="@dimen/margin_15"
                    android:src="@drawable/ic_arrows_sorting" />

                <ImageView
                    android:layout_width="@dimen/margin_4"
                    android:layout_height="@dimen/margin_4"
                    android:layout_gravity="right|top"
                    android:src="@drawable/red_circle_dot" />
            </FrameLayout>

            <FrameLayout
                android:id="@+id/layFilterIcon"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/margin_10">

                <ImageView
                    android:layout_width="@dimen/margin_15"
                    android:layout_height="@dimen/margin_15"
                    android:src="@drawable/ic_filters" />

                <ImageView
                    android:layout_width="@dimen/margin_4"
                    android:layout_height="@dimen/margin_4"
                    android:layout_gravity="right|top"
                    android:src="@drawable/red_circle_dot" />
            </FrameLayout>

            <androidx.appcompat.widget.SearchView
                android:id="@+id/edtSearch"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:queryHint="Search here" />

        </LinearLayout>

        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/layMain"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:visibility="visible"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/layFilters">


            <LinearLayout
                android:id="@+id/layStoreInfo"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/appcolor"
                android:gravity="center_vertical"
                android:orientation="vertical"
                android:padding="@dimen/margin_10"
                app:layout_constraintTop_toTopOf="parent">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:weightSum="2">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="@dimen/margin_10"
                        android:layout_weight="1"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="Booking Value"
                            android:textAlignment="viewStart"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="0/-"
                            android:textAlignment="viewEnd"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />
                    </LinearLayout>


                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_weight="1"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="Productive calls"
                            android:textAlignment="viewStart"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="0 / 7"
                            android:textAlignment="viewEnd"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />
                    </LinearLayout>


                </LinearLayout>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/margin_4"
                    android:orientation="horizontal"
                    android:weightSum="2">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="@dimen/margin_10"
                        android:layout_weight="1"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="Average SKU per outlet"
                            android:textAlignment="viewStart"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="1.00"
                            android:textAlignment="viewEnd"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />
                    </LinearLayout>


                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_weight="1"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="Number of cartons"
                            android:textAlignment="viewStart"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="0"
                            android:textAlignment="viewEnd"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />
                    </LinearLayout>


                </LinearLayout>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/margin_4"
                    android:orientation="horizontal"
                    android:weightSum="2">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="@dimen/margin_10"
                        android:layout_weight="1"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="Volume (Ltr)"
                            android:textAlignment="viewStart"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="0"
                            android:textAlignment="viewEnd"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />
                    </LinearLayout>


                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_weight="1"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="Weight (Kgs)"
                            android:textAlignment="viewStart"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />

                        <TextView
                            android:layout_width="@dimen/margin_0dp"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:maxLines="1"
                            android:text="0"
                            android:textAlignment="viewEnd"
                            android:textColor="@color/white"
                            android:textSize="@dimen/margin_8"
                            android:textStyle="bold" />
                    </LinearLayout>


                </LinearLayout>

            </LinearLayout>

            <LinearLayout
                android:id="@+id/layStoresType"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                app:layout_constraintTop_toBottomOf="@+id/layStoreInfo">


                <LinearLayout
                    android:id="@+id/layAllStores"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:paddingTop="@dimen/margin_10">

                    <TextView
                        android:id="@+id/tvAllStores"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:maxLines="1"
                        android:text="All Stores (7)"
                        android:textAlignment="center"
                        android:textColor="@color/language_text_color"
                        android:textSize="@dimen/margin_10"
                        android:textStyle="bold" />

                    <View
                        android:id="@+id/viewAllStores"
                        android:layout_width="match_parent"
                        android:layout_height="2dp"
                        android:layout_marginHorizontal="@dimen/margin_25"
                        android:layout_marginTop="@dimen/margin_10"
                        android:background="@color/light_gray"
                        android:maxLines="1" />

                </LinearLayout>

                <View
                    android:layout_width="1dp"
                    android:layout_height="match_parent"
                    android:layout_marginVertical="@dimen/margin_4"
                    android:background="@color/view_line" />

                <LinearLayout
                    android:id="@+id/layProductive"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:paddingTop="@dimen/margin_10">

                    <TextView
                        android:id="@+id/tvProductive"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:maxLines="1"
                        android:text="Productive (3)"
                        android:textAlignment="center"
                        android:textColor="@color/language_text_color"
                        android:textSize="@dimen/margin_10"
                        android:textStyle="bold" />

                    <View
                        android:id="@+id/viewProductive"
                        android:layout_width="match_parent"
                        android:layout_height="2dp"
                        android:layout_marginHorizontal="@dimen/margin_25"
                        android:layout_marginTop="@dimen/margin_10"
                        android:background="@color/light_gray"
                        android:maxLines="1"
                        android:visibility="invisible" />

                </LinearLayout>

                <View
                    android:layout_width="1dp"
                    android:layout_height="match_parent"
                    android:layout_marginVertical="@dimen/margin_4"
                    android:background="@color/view_line" />


                <LinearLayout
                    android:id="@+id/layNonProductive"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:paddingTop="@dimen/margin_10">

                    <TextView
                        android:id="@+id/tvNonProductive"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:maxLines="1"
                        android:text="Non-Productive (0)"
                        android:textAlignment="center"
                        android:textColor="@color/language_text_color"
                        android:textSize="@dimen/margin_10"
                        android:textStyle="bold" />

                    <View
                        android:id="@+id/viewNonProductive"
                        android:layout_width="match_parent"
                        android:layout_height="2dp"
                        android:layout_marginHorizontal="@dimen/margin_25"
                        android:layout_marginTop="@dimen/margin_10"
                        android:background="@color/light_gray"
                        android:maxLines="1"
                        android:visibility="invisible" />

                </LinearLayout>


            </LinearLayout>

            <View
                android:id="@+id/viewStoreType"
                android:layout_width="match_parent"
                android:layout_height="1dp"
                android:background="@color/view_line"
                app:layout_constraintTop_toBottomOf="@+id/layStoresType" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rcvVisits"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/viewStoreType"
                tools:listitem="@layout/visit_item" />

            <LinearLayout
                android:id="@+id/layPlaceHolder"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:gravity="center"
                android:orientation="vertical"
                android:visibility="gone"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/viewStoreType">

                <ImageView
                    android:layout_width="@dimen/margin_60"
                    android:layout_height="@dimen/margin_60"
                    android:src="@drawable/ic_store" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Not a single match"
                    android:textAlignment="center"
                    android:textColor="@color/language_text_color"
                    android:textSize="@dimen/margin_14"
                    android:textStyle="bold" />


            </LinearLayout>

        </androidx.constraintlayout.widget.ConstraintLayout>

        <LinearLayout
            android:id="@+id/layFiltersContainer"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:orientation="vertical"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/layFilters">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/margin_10"
                android:layout_gravity="end"
                android:layout_marginEnd="@dimen/margin_20"
                android:text="Clear All"
                android:textColor="@color/language_text_color"
                android:textStyle="bold" />

            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/margin_1"
                android:layout_marginTop="@dimen/margin_10"
                android:background="@color/view_line" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                android:layout_marginTop="@dimen/margin_20"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:weightSum="2">

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="@dimen/margin_10"
                        android:layout_height="@dimen/margin_10"
                        android:src="@drawable/circle_filters_back" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_marginEnd="@dimen/margin_20"
                        android:text="PJP"
                        android:textColor="@color/language_text_color"
                        android:textStyle="bold" />

                </LinearLayout>

                <TextView
                    android:id="@+id/tvFilterByPJP"
                    android:layout_width="@dimen/margin_0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:maxLines="1"
                    android:text="Tap to Select"
                    android:textAlignment="viewEnd"
                    android:textColor="@color/language_text_color"
                    android:textStyle="bold" />

            </LinearLayout>

            <com.nex3z.flowlayout.FlowLayout
                android:id="@+id/flowLayPJP"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                app:flChildSpacing="2dp"
                app:flRowSpacing="2dp" />


            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/margin_1"
                android:layout_marginTop="@dimen/margin_10"
                android:background="@color/view_line" />


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                android:layout_marginTop="@dimen/margin_10"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:weightSum="2">

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="@dimen/margin_10"
                        android:layout_height="@dimen/margin_10"
                        android:src="@drawable/circle_filters_back" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_marginEnd="@dimen/margin_20"
                        android:text="Locality"
                        android:textColor="@color/language_text_color"
                        android:textStyle="bold" />

                </LinearLayout>

                <TextView
                    android:id="@+id/tvFilterByLocality"
                    android:layout_width="@dimen/margin_0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:maxLines="1"
                    android:text="Tap to Select"
                    android:textAlignment="viewEnd"
                    android:textColor="@color/language_text_color"
                    android:textStyle="bold" />

            </LinearLayout>

            <com.nex3z.flowlayout.FlowLayout
                android:id="@+id/flowLayLocality"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                app:flChildSpacing="2dp"
                app:flRowSpacing="2dp" />


            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/margin_1"
                android:layout_marginTop="@dimen/margin_10"
                android:background="@color/view_line" />


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                android:layout_marginTop="@dimen/margin_10"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:weightSum="2">

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="@dimen/margin_10"
                        android:layout_height="@dimen/margin_10"
                        android:src="@drawable/circle_filters_back" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_marginEnd="@dimen/margin_20"
                        android:text="Sub-locality"
                        android:textColor="@color/language_text_color"
                        android:textStyle="bold" />

                </LinearLayout>

                <TextView
                    android:id="@+id/tvFilterBySubLocality"
                    android:layout_width="@dimen/margin_0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:maxLines="1"
                    android:text="Tap to Select"
                    android:textAlignment="viewEnd"
                    android:textColor="@color/language_text_color"
                    android:textStyle="bold" />

            </LinearLayout>

            <com.nex3z.flowlayout.FlowLayout
                android:id="@+id/flowLaySubLocality"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                app:flChildSpacing="2dp"
                app:flRowSpacing="2dp" />


            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/margin_1"
                android:layout_marginTop="@dimen/margin_10"
                android:background="@color/view_line" />


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                android:layout_marginTop="@dimen/margin_10"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:weightSum="2">

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="@dimen/margin_10"
                        android:layout_height="@dimen/margin_10"
                        android:src="@drawable/circle_filters_back" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_marginEnd="@dimen/margin_20"
                        android:maxLines="1"
                        android:text="Channel"
                        android:textColor="@color/language_text_color"
                        android:textStyle="bold" />

                </LinearLayout>

                <TextView
                    android:id="@+id/tvFilterByChannel"
                    android:layout_width="@dimen/margin_0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:maxLines="1"
                    android:text="Tap to Select"
                    android:textAlignment="viewEnd"
                    android:textColor="@color/language_text_color"
                    android:textStyle="bold" />

            </LinearLayout>

            <com.nex3z.flowlayout.FlowLayout
                android:id="@+id/flowLayChannel"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                app:flChildSpacing="2dp"
                app:flRowSpacing="2dp" />


            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/margin_1"
                android:layout_marginTop="@dimen/margin_10"
                android:background="@color/view_line" />


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                android:layout_marginTop="@dimen/margin_10"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:weightSum="2">

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="@dimen/margin_10"
                        android:layout_height="@dimen/margin_10"
                        android:src="@drawable/circle_filters_back" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_marginEnd="@dimen/margin_20"
                        android:text="Last Purchase"
                        android:textColor="@color/language_text_color"
                        android:textStyle="bold" />

                </LinearLayout>

                <TextView
                    android:id="@+id/tvFilterByLastPurchase"
                    android:layout_width="@dimen/margin_0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:maxLines="1"
                    android:text="Tap to Select"
                    android:textAlignment="viewEnd"
                    android:textColor="@color/language_text_color"
                    android:textStyle="bold" />

            </LinearLayout>


            <com.nex3z.flowlayout.FlowLayout
                android:id="@+id/flowLayLastPurchase"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                app:flChildSpacing="2dp"
                app:flRowSpacing="2dp" />


            <View
                android:layout_width="match_parent"
                android:layout_height="@dimen/margin_1"
                android:layout_marginTop="@dimen/margin_10"
                android:background="@color/view_line" />


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                android:layout_marginTop="@dimen/margin_10"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:weightSum="2">

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="@dimen/margin_10"
                        android:layout_height="@dimen/margin_10"
                        android:src="@drawable/circle_filters_back" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginStart="@dimen/margin_10"
                        android:layout_marginEnd="@dimen/margin_20"
                        android:text="Perfect Store Level"
                        android:textColor="@color/language_text_color"
                        android:textStyle="bold" />

                </LinearLayout>

                <TextView
                    android:id="@+id/tvFilterByPerfectStoreLevel"
                    android:layout_width="@dimen/margin_0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:maxLines="1"
                    android:text="Tap to Select"
                    android:textAlignment="viewEnd"
                    android:textColor="@color/language_text_color"
                    android:textStyle="bold" />

            </LinearLayout>

            <com.nex3z.flowlayout.FlowLayout
                android:id="@+id/flowLayPerfectStoreLevel"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="@dimen/margin_20"
                app:flChildSpacing="2dp"
                app:flRowSpacing="2dp" />


            <androidx.cardview.widget.CardView
                android:id="@+id/cardViewSubmit"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="20dp"
                app:cardBackgroundColor="@color/appcolor"
                app:cardCornerRadius="20dp"
                app:cardElevation="7dp"
                app:cardUseCompatPadding="true"
                app:rippleColor="@color/appcolor">


                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="?attr/selectableItemBackgroundBorderless"
                    android:paddingStart="20dp"
                    android:paddingTop="10dp"
                    android:paddingEnd="20dp"
                    android:paddingBottom="10dp"
                    android:text="OK"
                    android:textAlignment="center"
                    android:textAllCaps="false"
                    android:textColor="@color/white"
                    android:textSize="10dp" />


            </androidx.cardview.widget.CardView>


        </LinearLayout>


    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>

**Comment by nex3z** [comment]
The preview works on my machine. I'm using Android Studio Dolphin | 2021.3.1 Path 1, maybe try upgrading Android Studio?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5645004/199983727-a8484bce-8a74-4cfd-843f-4135a5d44e86.png">

**Comment by NexoVentas-Android** [comment]
tried after updating my IDE but yet issue occur same for me 
![Untitled](https://user-images.githubusercontent.com/94887681/200109594-fb03bde0-98a2-4d11-b327-8cbdc2c6d0dd.png)
