### ISSUE TITLE
app_name overwrites default app name value

### ISSUE THREAD

**Issue by tmtrademarked** [nex3z/FlowLayout#6]
Thanks for creating this library! It's very useful. I have one minor quarrel with it, however.

Using the "app_name" field for your library is somewhat dangerous. If other apps include your library and use "app_name" for their own strings, the string from this library might collide. This results in seeing "FlowLayout" on the launcher screen, which is not desired.

I'd strongly suggest either renaming the "app_name" string to something else, and consider prefixing your resources. (See https://medium.com/@maxirosson/how-to-improve-your-android-library-2e8b9fd6c090 for some additional context here)

**Comment by nex3z** [comment]
I've prefixed attributes with "fl" and removed the `app_name`. Thanks for the great advice.
