### ISSUE TITLE
Gradle sysnc errors

### ISSUE THREAD

**Issue by muzia** [nex3z/FlowLayout#8]
my develoption environment  is  “Android Studio：3.0  ；Gradle：4.1” ,when i  import this project ,it  displays  this  problem ,as follows:
 "Error:Unable to load class 'org.gradle.api.internal.component.Usage'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes."

**Comment by nex3z** [comment]
The bintray-release plugin is out dated. Update to version 0.7.0 should fix this issue.

In the root build.gradle file, change
```
classpath 'com.novoda:bintray-release:0.4.0'
```
to
```
classpath 'com.novoda:bintray-release:0.7.0'
```

I've also updated build tools and dependencies in 669d48c89bd02266aaa70dca3f0b4531461e35c6.
